import '@/globals.css';
import { ReactNode } from 'react';

import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<{ children: ReactNode }> = ({ children }) => (
  <html lang="pt-br">
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
